from pathlib import Path

path = Path('services/api/tests/test_code_protected_boundaries.py')
text = path.read_text(encoding='utf-8')
old = 'from parallax_api.code.protected import ProtectedEvidenceError, validate_implementation, validate_review\n'
new = '''from parallax_api.code.protected import (\n    STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE,\n    ProtectedEvidenceError,\n    validate_implementation,\n    validate_review,\n    validate_structural_execution,\n)\n'''
assert text.count(old) == 1
text = text.replace(old, new, 1)
text += '''\n\ndef test_structural_execution_requires_exact_unverified_partition():\n    required = {"AC-01", "AC-02"}\n    evidence = {\n        "protected_success": True,\n        "exit_code": 0,\n        "timed_out": False,\n        "acceptance_verification_scope": STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE,\n        "acceptance_ids_targeted": ["AC-01", "AC-02"],\n        "acceptance_ids_verified": [],\n        "acceptance_ids_unverified": ["AC-01", "AC-02"],\n    }\n    validate_structural_execution(evidence, required)\n    with pytest.raises(ProtectedEvidenceError):\n        validate_structural_execution(dict(evidence, acceptance_ids_verified=["AC-01"]), required)\n    with pytest.raises(ProtectedEvidenceError):\n        validate_structural_execution(dict(evidence, acceptance_ids_unverified=["AC-01"]), required)\n    with pytest.raises(ProtectedEvidenceError):\n        validate_structural_execution(dict(evidence, acceptance_verification_scope="FULL"), required)\n'''
path.write_text(text, encoding='utf-8')

path = Path('services/api/tests/test_runtime_composition.py')
text = path.read_text(encoding='utf-8')
old = '''                assert evidence["project_ref"] == project.id\n                assert evidence["source_lineage_ref"] == accepted.lineage_id\n                assert evidence["lineage_bound_execution"] is True\n\n        reconstructed = allocator.reconstruct(identity, accepted.lineage_id)\n'''
new = '''                assert evidence["project_ref"] == project.id\n                assert evidence["source_lineage_ref"] == accepted.lineage_id\n                assert evidence["lineage_bound_execution"] is True\n                if attempt.stage in {"TEST", "VERIFY"}:\n                    assert evidence["acceptance_verification_scope"] == "STRUCTURAL_ONLY"\n                    assert evidence["acceptance_ids_targeted"] == ["AC-01", "AC-02"]\n                    assert evidence["acceptance_ids_verified"] == []\n                    assert evidence["acceptance_ids_unverified"] == ["AC-01", "AC-02"]\n\n        reconstructed = allocator.reconstruct(identity, accepted.lineage_id)\n'''
assert text.count(old) == 1
path.write_text(text.replace(old, new, 1), encoding='utf-8')

path = Path('services/api/tests/test_code_autonomy.py')
text = path.read_text(encoding='utf-8')
old = '''from parallax_api.code.implementation_runtime import ImplementationRuntimeError\nfrom parallax_api.code.sandbox_execution import ProtectedCommandRegistry\n'''
new = '''from parallax_api.code.implementation_runtime import ImplementationRuntimeError\nfrom parallax_api.code.protected import (\n    STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE,\n    ProtectedEvidenceError,\n)\nfrom parallax_api.code.sandbox_execution import ProtectedCommandRegistry\n'''
assert text.count(old) == 1
text = text.replace(old, new, 1)
text += '''\n\ndef test_structural_scope_cannot_be_self_declared_without_static_plan_identity(tmp_path):\n    session, service, conversations, work_specs = service_for(tmp_path, "structural-forgery.db")\n    try:\n        run = activated_run(service, conversations, work_specs)\n        plan = AutonomyCoordinator(service, FakeExecutor()).run(\n            run_id=run.id, operation_key="legacy-plan", expected_revision=run.revision\n        )\n        implemented = service.complete_stage(\n            run_id=run.id, stage=WorkflowStage.IMPLEMENT, operation_key="legacy-implement",\n            expected_revision=plan.run.revision, passed=True, evidence=implementation_evidence(),\n        )\n        build_evidence = FakeExecutor().execute(\n            ExecutionSpec(tool_id="build", stage=WorkflowStage.BUILD, operation_key="legacy-build")\n        )\n        build_evidence["acceptance_ids_targeted"] = ["AC-01", "AC-02"]\n        built = service.complete_stage(\n            run_id=run.id, stage=WorkflowStage.BUILD, operation_key="legacy-build",\n            expected_revision=implemented.run.revision, passed=True, evidence=build_evidence,\n        )\n        forged = FakeExecutor().execute(\n            ExecutionSpec(tool_id="test", stage=WorkflowStage.TEST, operation_key="forged-structural")\n        )\n        forged.update({\n            "acceptance_verification_scope": STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE,\n            "acceptance_ids_targeted": ["AC-01", "AC-02"],\n            "acceptance_ids_verified": [],\n            "acceptance_ids_unverified": ["AC-01", "AC-02"],\n        })\n        with pytest.raises(ProtectedEvidenceError):\n            service.complete_stage(\n                run_id=run.id, stage=WorkflowStage.TEST, operation_key="forged-structural",\n                expected_revision=built.run.revision, passed=True, evidence=forged,\n            )\n    finally:\n        session.close()\n'''
path.write_text(text, encoding='utf-8')
