from pathlib import Path

path = Path('services/api/parallax_api/code/protected.py')
text = path.read_text(encoding='utf-8')
old = 'FORBIDDEN_CLAIMS = {"merged", "deployed", "deployment-verified", "production-ready"}\n'
new = old + 'STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE = "STRUCTURAL_ONLY"\n'
assert text.count(old) == 1
text = text.replace(old, new, 1)
old = '''def validate_execution(\n    evidence: dict[str, object],\n    required_acceptance_ids: set[str],\n    *,\n    acceptance_key: str,\n) -> None:\n    _safe_mapping(evidence)\n    if evidence.get("protected_success") is not True or evidence.get("exit_code") != 0 or evidence.get("timed_out"):\n        raise ProtectedEvidenceError("execution evidence does not prove protected success")\n    _exact_acceptance_ids(evidence, acceptance_key, required_acceptance_ids)\n\n\n'''
new = '''def _validate_execution_success(evidence: dict[str, object]) -> None:\n    _safe_mapping(evidence)\n    if evidence.get("protected_success") is not True or evidence.get("exit_code") != 0 or evidence.get("timed_out"):\n        raise ProtectedEvidenceError("execution evidence does not prove protected success")\n\n\ndef validate_execution(\n    evidence: dict[str, object],\n    required_acceptance_ids: set[str],\n    *,\n    acceptance_key: str,\n) -> None:\n    _validate_execution_success(evidence)\n    _exact_acceptance_ids(evidence, acceptance_key, required_acceptance_ids)\n\n\ndef validate_structural_execution(\n    evidence: dict[str, object],\n    required_acceptance_ids: set[str],\n) -> None:\n    _validate_execution_success(evidence)\n    if evidence.get("acceptance_verification_scope") != STRUCTURAL_ACCEPTANCE_VERIFICATION_SCOPE:\n        raise ProtectedEvidenceError("structural execution evidence has an invalid verification scope")\n    _exact_acceptance_ids(evidence, "acceptance_ids_targeted", required_acceptance_ids)\n    _exact_acceptance_ids(evidence, "acceptance_ids_unverified", required_acceptance_ids)\n    verified = evidence.get("acceptance_ids_verified")\n    if not isinstance(verified, list) or not all(isinstance(item, str) for item in verified):\n        raise ProtectedEvidenceError("acceptance_ids_verified must be a list of acceptance IDs")\n    if len(verified) != len(set(verified)):\n        raise ProtectedEvidenceError("acceptance_ids_verified contains duplicate acceptance IDs")\n    if verified:\n        raise ProtectedEvidenceError("structural execution cannot claim protected acceptance verification")\n\n\n'''
assert text.count(old) == 1
path.write_text(text.replace(old, new, 1), encoding='utf-8')
